---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: dansapp
        image: "nfestatechnologies/dansapp:${DOCKER_TAG}"
        state: Started
        published_ports:
          - 0.0.0.0:8081:8080
